theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo.svg"
  summary:
    position: hero
  search:
    active: false  