[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/2024-economie-de-l-esclavage/index.html"
to = "/livres-blancs/2024-economie-de-l-esclavage/"

[[redirects]]
from = "/2024-marketing-de-la-misere/index.html"
to = "/livres-blancs/2024-marketing-de-la-misere/"

[[redirects]]
from = "/2023-tamgour/index.html"
to = "/livres-blancs/2023-tamgour/"

[[redirects]]
from = "/livre-blancs/index.html"
to = "/livres-blancs/livre-blancs/"

[[redirects]]
from = "/2024-le-hydroriver/index.html"
to = "/livres-blancs/2024-le-hydroriver/"

[[redirects]]
from = "/accessibilite/index.html"
to = "/non-accessibilite/"

[[redirects]]
from = "/2023-zara/index.html"
to = "/livres-blancs/2023-zara/"

[[redirects]]
from = "/livres-blancs/economie-de-l-esclavage/index.html"
to = "/livres-blancs/2024-economie-de-l-esclavage/"

[[redirects]]
from = "/2023-eco-tromperie/index.html"
to = "/livres-blancs/2023-eco-tromperie/"

[[redirects]]
from = "/2023-on-te-voit/index.html"
to = "/livres-blancs/2023-on-te-voit/"

[[redirects]]
from = "/2023-spacecare-by-ab/index.html"
to = "/livres-blancs/2023-spacecare-by-ab/"

[[redirects]]
from = "/projets-davenir/index.html"
to = "/livres-blancs/projets-davenir/"

[[redirects]]
from = "/2023-sygmol/index.html"
to = "/livres-blancs/2023-sygmol/"

[[redirects]]
from = "/livres-blancs/2024-eduquer-pour-l-echec/index.html"
to = "/livres-blancs/2024-apprentissage-pour-l-echec/"

[[redirects]]
from = "/2023-l-ere-de-la-survie/index.html"
to = "/livres-blancs/2023-l-ere-de-la-survie/"

[[redirects]]
from = "/2022-douce-apocalypse/index.html"
to = "/livres-blancs/2022-douce-apocalypse/"

[[redirects]]
from = "/2024-credit-humain/index.html"
to = "/livres-blancs/2024-credit-humain/"

[[redirects]]
from = "/2024-economie-de-l-exploitation/index.html"
to = "/livres-blancs/2024-economie-de-l-exploitation/"

[[redirects]]
from = "/2024-apprentissage-pour-l-echec/index.html"
to = "/livres-blancs/2024-apprentissage-pour-l-echec/"

[[redirects]]
from = "/2023-l-apres-mediterranee/index.html"
to = "/livres-blancs/2023-l-apres-mediterranee/"

[[redirects]]
from = "/projets/economie-de-lesclavage-strategies-pour-accroitre-les-marges-dans-lindustrie-textile/index.html"
to = "/livres-blancs/"

[[redirects]]
from = "/2024-rearmement-demographique/index.html"
to = "/livres-blancs/2024-rearmement-demographique/"

[[redirects]]
from = "/projets/index.html"
to = "/livres-blancs/"

[[redirects]]
from = "/2024-industrie-de-la-dependance/index.html"
to = "/livres-blancs/2024-industrie-de-la-dependance/"

[[redirects]]
from = "/livres-blancs/2023-douce-apocalypse/index.html"
to = "/livres-blancs/2022-douce-apocalypse/"

[[redirects]]
from = "/2023-burger-king/index.html"
to = "/livres-blancs/2023-burger-king/"

